; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags = 
	-DARDUINO_LOOP_STACK_SIZE=16384
	-DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.12.0
	stm32duino/STM32duino VL53L4CX@^1.1.0
	adafruit/Adafruit Unified Sensor@^1.1.14
	adafruit/Adafruit FXOS8700@^2.2.2
	adafruit/Adafruit FXAS21002C@^2.2.1
